@host = http://localhost:3000

### Create a new message

POST {{host}}/messages
Content-Type: application/json

{
    "post_image": "https://upload.wikimedia.org/wikipedia/commons/9/90/Otto_Albert_Koch_Varusschlacht_1909.jpg",
    "user": "62d27450a34a9d28a71e2c53",
    "text": "Tutoburg was just German propaganda. We didn't loose in our 'special military operations' in Germania. Quite the opposite, we performed amazingly and obtained strategical victories, despite some tactical setbacks. The Cheruschi are trying to spread a lie. Varvs enjoys my full trust and confidence, as always. Victory to Rome!",
    "likes": 15000
}

### Get all messages

GET {{host}}/messages

### Get one message (add id)

GET {{host}}/messages/

### Get all messages from one user (add id)
GET {{host}}/messages/author/62d27450a34a9d28a71e2c53

### Update one message (add id)

PATCH {{host}}/messages/
Content-Type: application/json

{
    "key": "last_name",
    "value": "jjknxslk"
}

### Delete one message (add id)
DELETE {{host}}/messages/